
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId= "create_crystal_clear"
version="1.20.1 - 0.1.1e"
displayName="Create: Crystal Clear"
logoFile="logo.png"
description='''
Compatible with create 0.5.1.f
The Ultimate Glass Casing Experience
'''

[[dependencies.create_crystal_clear]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_crystal_clear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_crystal_clear]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"
